### ISSUE TITLE
Error using pixelwise_experiments.py

### ISSUE THREAD

**Issue by aabbas90** [constantinpape/elf#37]
Hi,

While running `example/multicut/performance/pixelwise_experiments.py` I encounter the following error:

> Traceback (most recent call last):
>   File "pixelwise_experiments.py", line 78, in <module>
>     main()
>   File "pixelwise_experiments.py", line 70, in main
>     res = pixelwise_performance_experiments(args.solvers)
>   File "pixelwise_experiments.py", line 19, in pixelwise_performance_experiments
>     local_uvs, local_weights = compute_grid_graph_affinity_features(grid_graph, affs[:3], offsets[:3])
>   File "/home/ahabbas/software/anaconda3/envs/elf/lib/python3.7/site-packages/elf-0.2.4-py3.7.egg/elf/segmentation/features.py", line 323, in compute_grid_graph_affinity_features
>     gndim = len(grid_graph.shape)
> AttributeError: 'nifty.graph._graph.UndirectedGridGraph3DSimpleNh' object has no attribute 'shape'

Also the function `grid_graph.affinitiesToEdgeMapWithOffsets` cannot be found. Possibly I need to install some other version of nifty? Thanks!

**Comment by constantinpape** [comment]
Oh, yes. Unfortunately some of the functionality is only available on the master branch of my fork right now: https://github.com/constantinpape/nifty.
Did you install from source or via conda?
If from source, you just need to switch to my master and reinstall (note that this needs c++17 now). Otherwise, I want to update the conda package soon, but I am waiting for some external contributions, so it might be a few weeks.
In the meantime, you could try to install from source, or I could serialize the extracted multicut problem for you and upload it.

**Comment by aabbas90** [comment]
Thanks, I now installed nifty from source and am able to run.
